# Generated by Django 2.0.1 on 2019-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
